version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mbr_db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${DB_PASSWORD:-YourDefaultStrong123!_Pwd}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mbr_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultConnection=Server=db;Database=MembranasDb;User Id=sa;Password=${DB_PASSWORD:-YourDefaultStrong123!_Pwd};TrustServerCertificate=True;
      - Jwt__Key=${JWT_SECRET:-EchesortMembranasAppSuperSeguroKey99A2024=}
      - Jwt__Audience=https://membranas.com
      - Jwt__Issuer=https://membranas.com
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mbr_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mssql_data:
